### ISSUE TITLE
How are your confidence intervals calculated?

### ISSUE THREAD

**Issue by DamienIrving** [georgebv/pyextremes#36]
I was reading through your excellent [online documentation](https://georgebv.github.io/pyextremes/) and one thing that was missing was a basic description of how your confidence intervals are calculated. I'm assuming this placeholder is where that information will go:  
https://github.com/georgebv/pyextremes/blob/master/docs/user-guide/12-confidence-intervals.md

I was wondering if there are plans to complete that documentation page (and the user guide more generally), or is the documentation no longer being actively developed?

**Comment by georgebv** [comment]
@DamienIrving confidence intervals are computed using the Monte Carlo method (for both MLE and MCMC). Documentation takes a lot of time which I currently don't have. I would appreciate any contributions though and would give full credit to the author.

**Comment by georgebv** [comment]
@oceanywalker here you go:

- `MLE`: https://github.com/georgebv/pyextremes/blob/a46be28c7d699f3cfa0eb5894dd9683572cdb5f1/src/pyextremes/models/model_mle.py#L164-L170
- `MCMC`: https://github.com/georgebv/pyextremes/blob/a46be28c7d699f3cfa0eb5894dd9683572cdb5f1/src/pyextremes/models/model_emcee.py#L203-L211
