### ISSUE TITLE
KS test gives incorrect test_statistic

### ISSUE THREAD

**Issue by eastjames** [georgebv/pyextremes#39]
First: thank you for creating and sharing this software.

**Describe the bug**
When performing a KS test on extremes selected with POT and a generalized Pareto distribution, the location parameter is not given to `scipy.stats.kstest`. As a result, `test_statistic` is incorrect and the result of the KS test may be incorrect.

**To Reproduce**
```bash
$ wget https://github.com/georgebv/pyextremes-notebooks/raw/master/data/battery_wl.csv
```
```python
import pyextremes as px
import pandas as pd


data = (
    pd
    .read_csv("battery_wl.csv", index_col=0, parse_dates=True)
    .squeeze('columns')
    .sort_index(ascending=True)
    .astype(float)
    .dropna()
)
data = data.loc[pd.to_datetime("1925"):]
data = data - (data.index.array - pd.to_datetime("1992")) / pd.to_timedelta("365.2425D") * 2.87e-3

model = px.EVA(data=data)

model.get_extremes(
    method="POT",
    extremes_type="high",
    threshold = 1.4,
    r = '12H'
)

model.fit_model()

model.test_ks()

```
output:
```
                     Kolmogorov-Smirnov Test                      
------------------------------------------------------------------
Null hypothesis: data follows genpareto distribution              
Alternative hypothesis: data doesn't follow genpareto distribution
                                                                  
Test statistic: D = 0.9906864591234011                            
p-value: 3.829434059334826e-179                                   
                                                                  
Significance level: 0.05                                          
Critical value: 0.14274059053041283                               
Critical region: reject null-hypothesis if D > 0.14274059053041283
                                                                  
Test result: data doesn't follow genpareto distribution           
------------------------------------------------------------------
```

Note: Test statistic returns `D = 0.9906864591234011 `

**Expected behavior**
Compute test statics directly with `scipy.stats.kstest`:
```python
from scipy import stats
import functools

# old test statistic
gpcdf = functools.partial(stats.genpareto.cdf,**model.model.fit_parameters) # fixed parameters not included
print(stats.kstest(model.extremes,gpcdf).statistic)
# 0.9906864591234011

# correct test statistic
gpcdf2 = functools.partial(
    stats.genpareto.cdf,
    **{'loc' if k=='floc' else k:v for k,v in model.distribution.fixed_parameters.items()}, # fixed parameters included
    **model.model.fit_parameters
)
print(stats.kstest(model.extremes,gpcdf2).statistic)
# 0.09295193640733063
```

**System:**
Python 3.10.4
```
  Operating System: CentOS Linux 7 (Core)
      Architecture: x86-64
```

**Comment by georgebv** [comment]
@eastjames good catch. Based on my review, the test itself is implemented correctly but `fit_parameters` passed to it in the `EVA` class are indeed incorrect (must be both fixed and free (aka fit) parameters). We need to provide a merged dict of fixed and free parameters in the `EVA.test_ks` method. Would you like to submit a pull request with this fix? I would appreciate a contribution, especially since you found the error and solution already.

**Comment by eastjames** [comment]
@georgebv apologies for my delay. Yes -- if it is not immediately urgent, I would be glad to submit a pull request with a fix in the next few weeks.

**Comment by georgebv** [comment]
@eastjames absolutely, no rush, contributions are welcome any time. Please ping me here whenever you prepare the PR

**Comment by georgebv** [comment]
@eastjames I know that you likely moved on, but reminding in case you are still interesting in contributing to the project. If not, no worries - let me know and I will close the issue.
