### ISSUE TITLE
Support for covariates

### ISSUE THREAD

**Issue by bbalaji-ucsd** [georgebv/pyextremes#54]
Any plan to support covariates for extreme value analysis similar to this R package:
https://cran.r-project.org/web/packages/extRemes/index.html

**Comment by georgebv** [comment]
This question was asked here before: https://github.com/georgebv/pyextremes/issues/30

If you would be willing to get this started, I will gladly help and review.

**Comment by bbalaji-ucsd** [comment]
Thank you George, I will investigate further to see if I can implement a simple version to get started.
