### ISSUE TITLE
Error in plot_parameter_stability()

### ISSUE THREAD

**Issue by cassin-edwin** [georgebv/pyextremes#68]
I have a continuous column data and wanted to plot plot_parameter_stability() from pyextremes.
But I am getting an error. When I used the same column for plot_mean_residual_life() it outputted the plot perfectly.

Error:
I had hidden the column name for confidential purposes
![image](https://github.com/georgebv/pyextremes/assets/22761661/c09d5c3e-0f34-41ba-94be-3a03570695de)

Sample values of the data:
![image](https://github.com/georgebv/pyextremes/assets/22761661/b1e29c90-4e52-4888-911a-b4a19550ec1e)

Code was run on the following versions:
 - Python version : 3.9.16
 - pyextremes - 2.3.1
 
 
 
 Please help.

**Comment by georgebv** [comment]
Please provide a self-contained code snippet that I can run to get the same error, I cannot help you if I cannot reproduce it.

**Comment by georgebv** [comment]
Your data is not time series. Please refer to this section for more details https://georgebv.github.io/pyextremes/quickstart/#read-data
