### ISSUE TITLE
Make pyextremes citable with zenodo?

### ISSUE THREAD

**Issue by eastjames** [georgebv/pyextremes#73]
Pyextremes is useful and flexible and it has been helpful in my research. Can it be made citable?

For example, github provides the option for creating persistent identifiers through zenodo: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

If you are not interested in creating the persistent identifier for the repository, is there another citation you could suggest for your software? In addition to the Coles 2001 extreme value theory text.

Thank you!

**Comment by georgebv** [comment]
Thank you, this is a great suggestion. I added `CITATION.cff` file to the repo so you should now be able to cite it like so:

![image](https://github.com/georgebv/pyextremes/assets/22249152/0576de96-9454-4238-9863-8d0cfc37c3d9)

Regarding Zenodo, I tried it, but unfortunately their app is asking for too many permissions for my GitHub account (admin access to webhooks, read/write access to ALL profile data) and I don't feel comfortable providing that.

**Comment by eastjames** [comment]
Thank you!

**Comment by eastjames** [comment]
Thank you again for adding the citation file. However, without a DOI its usefulness is limited, because many academic journals require a DOI and a permanent archive. Are you able to reconsider or consider other options that would create a DOI? I understand your hesitancy to link zenodo and as an alternate, I will permanently archive my fork of the code in a data repository to meet journal requirements.

**Comment by georgebv** [comment]
I'd gladly consider alternatives, zenodo is being unreasonable with the permissions they are asking for something like a simple repository reference. If you would like to link your pyextremes fork for that, you have my full support/approval/endorsement.
