### ISSUE TITLE
Digital Object Identifier for pyextremes

### ISSUE THREAD

**Issue by arfogg** [georgebv/pyextremes#80]
**Is your feature request related to a problem? Please describe.**
I work in academic space science research. When publishing research, journals are becoming more strict about citing the code that has been used, often requiring a digital object identifier (DOI). See example here:
https://www.agu.org/publish-with-agu/publish/author-resources/data-and-software-for-authors
Scroll to "Data & Software Citation":
"
Citations should include:
1. Author(s) or project name(s)
2. Date / Software published
3. Title / Software name
4. Data or software release/version (optional)
5. Bracketed description type (e.g., [Dataset], [Software], [Collection], [ComputationalNotebook])
6. Repository name / Publication venue
7. **DOI, persistent identifier, URL**
8. Retrieved date (required when using URL)

"

**Describe the solution you'd like**
It would be really great if you could generate a DOI for new releases of pyextremes. It's quite easy to do, instructions here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content. An added benefit is it would give you an indication of where/how your great package is being used in academic literature.

**Comment by georgebv** [comment]
@arfogg I understand why you need this, this topic was previously discussed here https://github.com/georgebv/pyextremes/issues/73

Until zenodo resolves permission issues I cannot authorize this

**Comment by arfogg** [comment]
@georgebv thanks for your reply! Totally understand your issue with permissions etc.
If I find any other/better ways to make a DOI I will let you know!
Alexandra
